# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI
on: [push, pull_request]
jobs:
    build:
        runs-on: ${{ matrix.os }}

        services:
            postgres:
                image: postgres
                env:
                    POSTGRES_USER: postgres
                    POSTGRES_PASSWORD: postgres
                    POSTGRES_DB: ci
                    ports:
                        - 5432:5432
                options: >-
                    --health-cmd pg_isready
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5

        strategy:
            matrix:
                node-version: [10.x, 12.x]
                os: [ubuntu-16.04, ubuntu-18.04, ubuntu-latest]
        steps:
            - uses: actions/checkout@v2

            - name: Cache node modules
              uses: actions/cache@v1
              env:
                  cache-name: cache-node-modules
              with:
                  path: ~/.npm # npm cache files are stored in `~/.npm` on Linux/macOS
                  key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-build-${{ env.cache-name }}-
                      ${{ runner.os }}-build-
                      ${{ runner.os }}-

            - name: Install Dependencies From package-lock.json File
              run: npm ci

            - name: Install database-specific packages
              run: npm install pg pg-native

            - name: Build on postgres
              run: npm run build
              env:
                  SEQUELIZE_URL: postgres://postgres:postgres@localhost:${{ job.services.postgres.ports[5432] }}/ci

            - name: Test on postgres
              run: npm test
              env:
                  SEQUELIZE_URL: postgres://postgres:postgres@localhost:${{ job.services.postgres.ports[5432] }}/ci
